Model:
    name: "InSPyReNet_SwinB"
    depth: 64
    pretrained: False
    base_size: [384, 384]
    threshold: 512

Train:
    Dataset:
        type: "RGB_Dataset"
        root: "/home/jupyter/transparent-new"
        sets: [
              'Train_Dataset'
              ]
        transforms:
            static_resize: 
                size: [384, 384]
            random_scale_crop:
                range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: False
            random_rotate:
                range: [-10, 10]
            random_image_enhance:
                methods: ['contrast', 'sharpness', 'brightness']
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
            
    Dataloader:
        batch_size: 6
        shuffle: True
        num_workers: 8
        pin_memory: False
    Optimizer:
        type: "Adam"
        lr: 1.0e-06
        weight_decay: 0.0
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 60
        gamma: 0.9
        minimum_lr: 1.0e-07
        warmup_iteration: 12000
    Checkpoint:
        checkpoint_epoch: 1
        checkpoint_dir: "/home/jupyter/InSPyReNet/checkpoint"
    Debug:
        keys: ['saliency', 'laplacian']
    
Test:
    Dataset:
        type: "RGB_Dataset"
        root: "/home/jupyter/transparent-new"
        sets: [
              'Test_Dataset'
              ]
        transforms:
            dynamic_resize:
                L: 1280
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 1
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "/home/jupyter/InSPyReNet/checkpoint"

Eval:
    gt_root: "/home/jupyter/transparent-new"
    pred_root: "/home/jupyter/InSPyReNet/checkpoint"
    result_path: "/home/jupyter/InSPyReNet/results"
    datasets: [
              'Test_Dataset'
              ]
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm', 'mBA']
    
Inference:
    Dataset:
        type: "ImageLoader"
        source: "/content/images"
        dest: "/content/output"
         
        transforms:
            static_resize: 
                size: [384, 384]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 1
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "checkpoint/latest_35.pth"
        device: "cpu"
    
Video:
    Dataset:
        type: "ImageLoader"
        root: "/home/jupyter/InSPyReNet_prior/video"
        frame_folder: "frames"
        sets: [
              'Test_Dataset'
              ]
        transforms:
            static_resize: 
                size: [384, 384]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 1
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "/home/jupyter/InSPyReNet_prior/video/2023-01-23-19-16-20-nw"
    
